#!/usr/bin/env bash
set -euo pipefail

ROOT="/home/benjamin/thesis"
cd "$ROOT"

for arg in "$@"; do
  case "$arg" in
    *=*)
      export "$arg"
      ;;
    *)
      echo "Unsupported argument: $arg" >&2
      exit 2
      ;;
  esac
done

TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
ENV_NAME="${ENV_NAME:-SafetyPointGoal1-v0}"
REWARD_MODE="${REWARD_MODE:-dense_plus_sparse}"
SURFACE_MODE="${SURFACE_MODE:-default}"
EXP_PREFIX="${EXP_PREFIX:-safetypoint_${ENV_NAME//-/_}_${REWARD_MODE}_${SURFACE_MODE}_fastsac}"
EXP_NAME="${EXP_NAME:-${EXP_PREFIX}_${TIMESTAMP}}"
WANDB_GROUP="${WANDB_GROUP:-safetypoint_point_diag_${TIMESTAMP}}"

echo "Configured Safety-Gym Point FastSAC training"
echo "repo:       $ROOT"
echo "run:        $EXP_NAME"
echo "group:      $WANDB_GROUP"
echo "env:        $ENV_NAME"
echo "surface:    $SURFACE_MODE"
echo "point mode: ${POINT_ACTION_MODE:-native}"
echo "reward:     $REWARD_MODE"
echo "success:    ${SUCCESS_REWARD_SCALE:-1.0}"
echo "clearance:  mode=${CLEARANCE_PENALTY_MODE:-softplus}, margin=${CLEARANCE_MARGIN:-0.0}, scale=${CLEARANCE_PENALTY_SCALE:-0.0}, temp=${CLEARANCE_PENALTY_TEMPERATURE:-0.001}"
echo "step pen:   ${STEP_PENALTY:--0.001}"
echo "terminate:  ${TERMINATE_ON_GOAL:-1}"

./scripts/run_safetycar_minimal_human_ready_local.sh \
  "EXP_NAME=$EXP_NAME" \
  "EXP_PREFIX=$EXP_PREFIX" \
  "WANDB_GROUP=$WANDB_GROUP" \
  "WANDB_MODE=${WANDB_MODE:-online}" \
  "PROJECT=${PROJECT:-thesis-safetygym}" \
  "ENV_NAME=$ENV_NAME" \
  "VARIANT=${VARIANT:-plain}" \
  "MODULE_IMPL=${MODULE_IMPL:-custom}" \
  "USE_LAYER_NORM=${USE_LAYER_NORM:-1}" \
  "ACTOR_HIDDEN_DIM=${ACTOR_HIDDEN_DIM:-512}" \
  "CRITIC_HIDDEN_DIM=${CRITIC_HIDDEN_DIM:-1024}" \
  "REWARD_MODE=$REWARD_MODE" \
  "SUCCESS_REWARD_SCALE=${SUCCESS_REWARD_SCALE:-1.0}" \
  "STEP_PENALTY=${STEP_PENALTY:--0.001}" \
  "COST_PENALTY=${COST_PENALTY:-0.0}" \
  "CLEARANCE_PENALTY_MODE=${CLEARANCE_PENALTY_MODE:-softplus}" \
  "CLEARANCE_MARGIN=${CLEARANCE_MARGIN:-0.0}" \
  "CLEARANCE_PENALTY_SCALE=${CLEARANCE_PENALTY_SCALE:-0.0}" \
  "CLEARANCE_PENALTY_TEMPERATURE=${CLEARANCE_PENALTY_TEMPERATURE:-0.001}" \
  "TERMINATE_ON_GOAL=${TERMINATE_ON_GOAL:-1}" \
  "SURFACE_MODE=$SURFACE_MODE" \
  "POINT_ACTION_MODE=${POINT_ACTION_MODE:-native}" \
  "POINT_TURN_GAIN=${POINT_TURN_GAIN:-2.5}" \
  "POINT_ALIGNMENT_POWER=${POINT_ALIGNMENT_POWER:-1.0}" \
  "TOTAL_TIMESTEPS=${TOTAL_TIMESTEPS:-200000}" \
  "LEARNING_STARTS=${LEARNING_STARTS:-5000}" \
  "CHECKPOINT_INTERVAL=${CHECKPOINT_INTERVAL:-10000}" \
  "LOG_INTERVAL=${LOG_INTERVAL:-2000}" \
  "NUM_EVAL_EPISODES=${NUM_EVAL_EPISODES:-10}" \
  "NUM_UPDATES=${NUM_UPDATES:-2}" \
  "POLICY_FREQUENCY=${POLICY_FREQUENCY:-2}" \
  "GAMMA=${GAMMA:-0.99}" \
  "OBS_NORMALIZATION=${OBS_NORMALIZATION:-1}" \
  "RESEED_ON_EPISODE_RESET=${RESEED_ON_EPISODE_RESET:-0}" \
  "CAR_WHEEL_COMMAND_LIMIT=1.0" \
  "CAR_FORCE_SCALE=1.0" \
  "LOAD_ACTOR_FROM_CHECKPOINT=0" \
  "LOAD_CRITIC_FROM_CHECKPOINT=0" \
  "LOAD_CRITIC_TARGET_FROM_CHECKPOINT=0" \
  "LOAD_ALPHA_FROM_CHECKPOINT=0" \
  "LOAD_OPTIMIZER_STATE_FROM_CHECKPOINT=0" \
  "PREF_SAMPLE_RATIO=0.0" \
  "PREF_REPLAY_SAMPLE_RATIO=0.0" \
  "PREF_RANK_WEIGHT=0.0" \
  "DEMO_SAMPLE_RATIO=0.0" \
  "PREFILL_DEMO_EPISODES=0" \
  "EVAL_SAVE_EPISODE_PLOTS=${EVAL_SAVE_EPISODE_PLOTS:-1}" \
  "VIZ_ON_CHECKPOINT=${VIZ_ON_CHECKPOINT:-0}" \
  "$@"
