#!/usr/bin/env bash
set -euo pipefail

ROOT="/home/benjamin/thesis"
cd "$ROOT"

VARIANT="${VARIANT:-hilserl}"
INIT_CHECKPOINT_PATH="${INIT_CHECKPOINT_PATH:-}"
AUTO_RESOLVE_INIT_CHECKPOINT="${AUTO_RESOLVE_INIT_CHECKPOINT:-1}"
PRETRAIN_REPLAY_DATASET_PATH="${PRETRAIN_REPLAY_DATASET_PATH:-}"
EXPERIMENT_TAG="${EXPERIMENT_TAG:-safetycar_min_stage2}"
TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
WANDB_MODE="${WANDB_MODE:-online}"
PROJECT="${PROJECT:-thesis-safetygym}"
WANDB_GROUP="${WANDB_GROUP:-${EXPERIMENT_TAG}}"
EXP_PREFIX="${EXP_PREFIX:-${EXPERIMENT_TAG}_${VARIANT}}"
EXP_NAME="${EXP_NAME:-${EXP_PREFIX}_${TIMESTAMP}}"

if [[ -z "${INIT_CHECKPOINT_PATH}" && "${AUTO_RESOLVE_INIT_CHECKPOINT}" == "1" ]]; then
  shopt -s nullglob
  matches=(/home/benjamin/thesis/models/safetygym_minimal/*/final.pt)
  shopt -u nullglob
  if [[ ${#matches[@]} -gt 0 ]]; then
    INIT_CHECKPOINT_PATH="${matches[-1]}"
    echo "Auto-resolved latest minimal checkpoint: ${INIT_CHECKPOINT_PATH}"
  fi
fi

if [[ -z "${INIT_CHECKPOINT_PATH}" ]]; then
  echo "INIT_CHECKPOINT_PATH must point to a rebuilt minimal checkpoint." >&2
  exit 2
fi

DEMO_DATASET_TARGET="${DEMO_DATASET_TARGET:-variant}"
DEMO_SAMPLE_RATIO_DEFAULT="0.0"
STORE_INTERVENED_DEFAULT="0"
PREF_SAMPLE_RATIO_DEFAULT="0.0"
PREF_RANK_WEIGHT_DEFAULT="0.0"

case "${VARIANT}" in
  own)
    PREF_SAMPLE_RATIO_DEFAULT="0.5"
    PREF_RANK_WEIGHT_DEFAULT="1.0"
    DEMO_DATASET_TARGET="${DEMO_DATASET_TARGET:-variant}"
    ;;
  hilserl)
    DEMO_SAMPLE_RATIO_DEFAULT="0.5"
    STORE_INTERVENED_DEFAULT="1"
    DEMO_DATASET_TARGET="${DEMO_DATASET_TARGET:-variant}"
    ;;
  pvp)
    DEMO_DATASET_TARGET="${DEMO_DATASET_TARGET:-variant}"
    ;;
  *)
    echo "Unsupported VARIANT=${VARIANT}. Use one of: own, hilserl, pvp." >&2
    exit 2
    ;;
esac

VARIANT="$VARIANT" \
USE_INTERVENTION="${USE_INTERVENTION:-1}" \
HUMAN_INPUT_DEVICE="${HUMAN_INPUT_DEVICE:-gamepad}" \
GAMEPAD_MODE="${GAMEPAD_MODE:-connect}" \
GAMEPAD_HOST="${GAMEPAD_HOST:-127.0.0.1}" \
GAMEPAD_PORT="${GAMEPAD_PORT:-8793}" \
RENDER_MODE="${RENDER_MODE:-human}" \
REWARD_MODE="${REWARD_MODE:-sparse}" \
INIT_CHECKPOINT_PATH="${INIT_CHECKPOINT_PATH}" \
LOAD_ACTOR_FROM_CHECKPOINT="${LOAD_ACTOR_FROM_CHECKPOINT:-1}" \
LOAD_CRITIC_FROM_CHECKPOINT="${LOAD_CRITIC_FROM_CHECKPOINT:-1}" \
LOAD_CRITIC_TARGET_FROM_CHECKPOINT="${LOAD_CRITIC_TARGET_FROM_CHECKPOINT:-1}" \
LOAD_ALPHA_FROM_CHECKPOINT="${LOAD_ALPHA_FROM_CHECKPOINT:-1}" \
DEMO_DATASET_PATH="${PRETRAIN_REPLAY_DATASET_PATH}" \
DEMO_DATASET_TARGET="${DEMO_DATASET_TARGET}" \
DEMO_SAMPLE_RATIO="${DEMO_SAMPLE_RATIO:-${DEMO_SAMPLE_RATIO_DEFAULT}}" \
STORE_INTERVENED_IN_DEMO_BUFFER="${STORE_INTERVENED_IN_DEMO_BUFFER:-${STORE_INTERVENED_DEFAULT}}" \
PREF_SAMPLE_RATIO="${PREF_SAMPLE_RATIO:-${PREF_SAMPLE_RATIO_DEFAULT}}" \
PREF_RANK_WEIGHT="${PREF_RANK_WEIGHT:-${PREF_RANK_WEIGHT_DEFAULT}}" \
PREF_SAMPLING_MODE="${PREF_SAMPLING_MODE:-linked}" \
PREF_LOSS_TYPE="${PREF_LOSS_TYPE:-lagrangian}" \
PREF_STOPGRAD_POSITIVE="${PREF_STOPGRAD_POSITIVE:-1}" \
OBS_NORMALIZATION="${OBS_NORMALIZATION:-1}" \
SCALE_ACTOR_TO_ENV_BOUNDS="${SCALE_ACTOR_TO_ENV_BOUNDS:-1}" \
TOTAL_TIMESTEPS="${TOTAL_TIMESTEPS:-50000}" \
CHECKPOINT_INTERVAL="${CHECKPOINT_INTERVAL:-5000}" \
PROJECT="$PROJECT" \
WANDB_MODE="$WANDB_MODE" \
WANDB_GROUP="$WANDB_GROUP" \
EXP_PREFIX="$EXP_PREFIX" \
EXP_NAME="$EXP_NAME" \
/home/benjamin/thesis/scripts/run_safetycar_minimal_human_ready_local.sh
