#!/usr/bin/env bash
set -euo pipefail

ROOT="/home/benjamin/thesis"
cd "$ROOT"

for arg in "$@"; do
  case "$arg" in
    *=*)
      export "$arg"
      ;;
    *)
      echo "Unsupported argument: $arg" >&2
      exit 2
      ;;
  esac
done

TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"

export EXP_PREFIX="${EXP_PREFIX:-safetycar_scriptedgeo_bc_probe}"
export ENV_NAME="${ENV_NAME:-SafetyCarGoal1-v0}"
export TOTAL_TIMESTEPS="${TOTAL_TIMESTEPS:-30000}"
export CHECKPOINT_INTERVAL="${CHECKPOINT_INTERVAL:-10000}"
export LOG_INTERVAL="${LOG_INTERVAL:-1000}"
export NUM_EVAL_EPISODES="${NUM_EVAL_EPISODES:-5}"

export VARIANT="${VARIANT:-plain}"
export LEARNING_STARTS="${LEARNING_STARTS:-1000000000}"
export NUM_UPDATES="${NUM_UPDATES:-0}"
export PREF_SAMPLE_RATIO="${PREF_SAMPLE_RATIO:-0.0}"
export PREF_RANK_WEIGHT="${PREF_RANK_WEIGHT:-0.0}"
export DEMO_SAMPLE_RATIO="${DEMO_SAMPLE_RATIO:-0.0}"
export PREFILL_DEMO_EPISODES="${PREFILL_DEMO_EPISODES:-0}"
export DEMO_PRETRAIN_UPDATES="${DEMO_PRETRAIN_UPDATES:-0}"

export INIT_CHECKPOINT_PATH="${INIT_CHECKPOINT_PATH:-$ROOT/models/safetygym_minimal/safetycar_scriptedgeo_bc70k_shapedrl_finetune_30k_20260515/step_10000.pt}"
export LOAD_ACTOR_FROM_CHECKPOINT="${LOAD_ACTOR_FROM_CHECKPOINT:-1}"
export LOAD_CRITIC_FROM_CHECKPOINT="${LOAD_CRITIC_FROM_CHECKPOINT:-0}"
export LOAD_CRITIC_TARGET_FROM_CHECKPOINT="${LOAD_CRITIC_TARGET_FROM_CHECKPOINT:-0}"
export LOAD_ALPHA_FROM_CHECKPOINT="${LOAD_ALPHA_FROM_CHECKPOINT:-0}"
export LOAD_OPTIMIZER_STATE_FROM_CHECKPOINT="${LOAD_OPTIMIZER_STATE_FROM_CHECKPOINT:-0}"

export MODULE_IMPL="${MODULE_IMPL:-custom}"
export ACTOR_HIDDEN_DIM="${ACTOR_HIDDEN_DIM:-256}"
export CRITIC_HIDDEN_DIM="${CRITIC_HIDDEN_DIM:-512}"
export USE_LAYER_NORM="${USE_LAYER_NORM:-1}"
export OBS_NORMALIZATION="${OBS_NORMALIZATION:-1}"
export OBS_MASK_MODE="${OBS_MASK_MODE:-privileged_geometry}"
export REWARD_MODE="${REWARD_MODE:-dense}"
export DENSE_REWARD_SCALE="${DENSE_REWARD_SCALE:-1.0}"
export SUCCESS_REWARD_SCALE="${SUCCESS_REWARD_SCALE:-0.0}"
export STEP_PENALTY="${STEP_PENALTY:-0.0}"
export COST_PENALTY="${COST_PENALTY:-0.0}"
export CLEARANCE_PENALTY_SCALE="${CLEARANCE_PENALTY_SCALE:-0.0}"
export CLEARANCE_MARGIN="${CLEARANCE_MARGIN:-0.0}"
export TERMINATE_ON_GOAL="${TERMINATE_ON_GOAL:-1}"
export RESEED_ON_EPISODE_RESET="${RESEED_ON_EPISODE_RESET:-0}"

export CAR_WHEEL_COMMAND_LIMIT="${CAR_WHEEL_COMMAND_LIMIT:-1.0}"
export CAR_FORCE_SCALE="${CAR_FORCE_SCALE:-1.0}"
export CAR_ACTION_MODE="${CAR_ACTION_MODE:-raw_wheels}"
export SCALE_ACTOR_TO_ENV_BOUNDS="${SCALE_ACTOR_TO_ENV_BOUNDS:-1}"

export RENDER_MODE="${RENDER_MODE:-none}"
export ENV_FPS_LIMIT="${ENV_FPS_LIMIT:-0}"
export CONTROLLER_FPS_LIMIT="${CONTROLLER_FPS_LIMIT:-0}"
export VIZ_ON_CHECKPOINT="${VIZ_ON_CHECKPOINT:-0}"
export EVAL_SAVE_EPISODE_PLOTS="${EVAL_SAVE_EPISODE_PLOTS:-0}"

export USE_INTERVENTION="${USE_INTERVENTION:-1}"
export HUMAN_INPUT_DEVICE="${HUMAN_INPUT_DEVICE:-scripted_geo}"
export TEACHER_OVERRIDE_MODE="${TEACHER_OVERRIDE_MODE:-clearance_or_progress}"
export TEACHER_OVERRIDE_CLEARANCE_THRESHOLD="${TEACHER_OVERRIDE_CLEARANCE_THRESHOLD:-0.08}"
export TEACHER_OVERRIDE_CLEARANCE_EXIT_THRESHOLD="${TEACHER_OVERRIDE_CLEARANCE_EXIT_THRESHOLD:-0.14}"
export TEACHER_PROGRESS_SCORE_MODE="${TEACHER_PROGRESS_SCORE_MODE:-euclidean}"
export TEACHER_PROGRESS_TRIGGER_MODE="${TEACHER_PROGRESS_TRIGGER_MODE:-not_improving}"
export TEACHER_PROGRESS_RELEASE_MODE="${TEACHER_PROGRESS_RELEASE_MODE:-improve}"
export TEACHER_PROGRESS_BAD_STEPS="${TEACHER_PROGRESS_BAD_STEPS:-3}"
export TEACHER_PROGRESS_GOOD_STEPS="${TEACHER_PROGRESS_GOOD_STEPS:-5}"
export TEACHER_PROGRESS_EPSILON="${TEACHER_PROGRESS_EPSILON:-0.0005}"

export EXPORT_REPLAY_DATASET_INTERVAL="${EXPORT_REPLAY_DATASET_INTERVAL:-10000}"
export EXPORT_REPLAY_DATASET_LABEL="${EXPORT_REPLAY_DATASET_LABEL:-scriptedgeo_clearance_or_progress_replay}"
export EXPORT_FINAL_REPLAY_DATASET="${EXPORT_FINAL_REPLAY_DATASET:-1}"
export BC_EVAL_INTERVAL="${BC_EVAL_INTERVAL:-10000}"
export BC_EVAL_EPOCHS="${BC_EVAL_EPOCHS:-20}"
export BC_EVAL_BATCH_SIZE="${BC_EVAL_BATCH_SIZE:-256}"
export BC_EVAL_CONTEXT_LEN="${BC_EVAL_CONTEXT_LEN:-8}"
export BC_EVAL_NUM_EPISODES="${BC_EVAL_NUM_EPISODES:-10}"
export BC_EVAL_RENDER_MODE="${BC_EVAL_RENDER_MODE:-none}"
export BC_EVAL_FPS="${BC_EVAL_FPS:-0}"
export BC_EVAL_DEVICE="${BC_EVAL_DEVICE:-cpu}"
export BC_EVAL_STUDENT_POLICY="${BC_EVAL_STUDENT_POLICY:-checkpoint}"
export BC_EVAL_STUDENT_CHECKPOINT_PATH="${BC_EVAL_STUDENT_CHECKPOINT_PATH:-$INIT_CHECKPOINT_PATH}"

export WANDB_MODE="${WANDB_MODE:-online}"
export PROJECT="${PROJECT:-thesis-safetygym}"
export WANDB_GROUP="${WANDB_GROUP:-safetycar_scriptedgeo_bc_probe}"

"$ROOT/scripts/run_safetycar_minimal_human_ready_local.sh" "TIMESTAMP=$TIMESTAMP"
