#!/usr/bin/env bash
set -euo pipefail

ROOT="/home/benjamin/thesis"
cd "$ROOT"

TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
WANDB_MODE="${WANDB_MODE:-online}"
PROJECT="${PROJECT:-thesis-safetygym}"
WANDB_GROUP="${WANDB_GROUP:-safetycar_min_own_demo20_${TIMESTAMP}}"
EXP_PREFIX="${EXP_PREFIX:-safetycar_min_own_gamepad_dense_demo20}"
EXP_NAME="${EXP_NAME:-${EXP_PREFIX}_${TIMESTAMP}}"

VARIANT=own \
USE_INTERVENTION=1 \
HUMAN_INPUT_DEVICE="${HUMAN_INPUT_DEVICE:-gamepad}" \
GAMEPAD_MODE="${GAMEPAD_MODE:-connect}" \
GAMEPAD_HOST="${GAMEPAD_HOST:-127.0.0.1}" \
GAMEPAD_PORT="${GAMEPAD_PORT:-8793}" \
RENDER_MODE="${RENDER_MODE:-human}" \
REWARD_MODE="${REWARD_MODE:-dense}" \
PREFILL_DEMO_EPISODES="${PREFILL_DEMO_EPISODES:-20}" \
PREFILL_MAX_STEPS_PER_EPISODE="${PREFILL_MAX_STEPS_PER_EPISODE:-0}" \
PREFILL_POLICY="${PREFILL_POLICY:-zero}" \
PREF_SAMPLING_MODE="${PREF_SAMPLING_MODE:-linked}" \
PREF_SAMPLE_RATIO="${PREF_SAMPLE_RATIO:-0.5}" \
PREF_RANK_WEIGHT="${PREF_RANK_WEIGHT:-1.0}" \
PREF_RANK_MARGIN="${PREF_RANK_MARGIN:-0.1}" \
PREF_LOSS_TYPE="${PREF_LOSS_TYPE:-lagrangian}" \
PREF_LAMBDA_INIT="${PREF_LAMBDA_INIT:-1.0}" \
PREF_LAMBDA_LR="${PREF_LAMBDA_LR:-1e-3}" \
PREF_LAMBDA_MAX="${PREF_LAMBDA_MAX:-10.0}" \
PREF_LAMBDA_EMA="${PREF_LAMBDA_EMA:-0.9}" \
PREF_VIOLATION_CLIP="${PREF_VIOLATION_CLIP:-10.0}" \
PREF_VIOLATION_TARGET="${PREF_VIOLATION_TARGET:-0.0}" \
PREF_LAGRANGIAN_VIOLATION_TYPE="${PREF_LAGRANGIAN_VIOLATION_TYPE:-hinge}" \
PREF_STOPGRAD_POSITIVE="${PREF_STOPGRAD_POSITIVE:-1}" \
STORE_INTERVENED_IN_DEMO_BUFFER="${STORE_INTERVENED_IN_DEMO_BUFFER:-1}" \
OBS_NORMALIZATION="${OBS_NORMALIZATION:-1}" \
SCALE_ACTOR_TO_ENV_BOUNDS="${SCALE_ACTOR_TO_ENV_BOUNDS:-1}" \
CHECKPOINT_INTERVAL="${CHECKPOINT_INTERVAL:-5000}" \
TOTAL_TIMESTEPS="${TOTAL_TIMESTEPS:-50000}" \
PROJECT="$PROJECT" \
WANDB_MODE="$WANDB_MODE" \
WANDB_GROUP="$WANDB_GROUP" \
EXP_PREFIX="$EXP_PREFIX" \
EXP_NAME="$EXP_NAME" \
/home/benjamin/thesis/scripts/run_safetycar_minimal_human_ready_local.sh
