#!/usr/bin/env bash
set -euo pipefail

ROOT="/home/benjamin/thesis"
cd "$ROOT"

TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
EXP_PREFIX="${EXP_PREFIX:-safetycar_min_own_gamepad_from_scratch}"
EXP_NAME="${EXP_NAME:-${EXP_PREFIX}_${TIMESTAMP}}"

VARIANT=own \
USE_INTERVENTION=1 \
HUMAN_INPUT_DEVICE="${HUMAN_INPUT_DEVICE:-gamepad}" \
GAMEPAD_MODE="${GAMEPAD_MODE:-connect}" \
GAMEPAD_HOST="${GAMEPAD_HOST:-127.0.0.1}" \
GAMEPAD_PORT="${GAMEPAD_PORT:-8793}" \
RENDER_MODE="${RENDER_MODE:-human}" \
MODULE_IMPL="${MODULE_IMPL:-custom}" \
ACTOR_HIDDEN_DIM="${ACTOR_HIDDEN_DIM:-512}" \
CRITIC_HIDDEN_DIM="${CRITIC_HIDDEN_DIM:-1024}" \
TOTAL_TIMESTEPS="${TOTAL_TIMESTEPS:-50000}" \
CHECKPOINT_INTERVAL="${CHECKPOINT_INTERVAL:-5000}" \
LEARNING_STARTS="${LEARNING_STARTS:-5000}" \
REWARD_MODE="${REWARD_MODE:-dense}" \
STEP_PENALTY="${STEP_PENALTY:--0.001}" \
COST_PENALTY="${COST_PENALTY:-0.0}" \
GAMMA="${GAMMA:-0.99}" \
OBS_NORMALIZATION="${OBS_NORMALIZATION:-1}" \
SCALE_ACTOR_TO_ENV_BOUNDS="${SCALE_ACTOR_TO_ENV_BOUNDS:-1}" \
PREF_SAMPLE_RATIO="${PREF_SAMPLE_RATIO:-0.5}" \
PREF_RANK_WEIGHT="${PREF_RANK_WEIGHT:-1.0}" \
PREF_SAMPLING_MODE="${PREF_SAMPLING_MODE:-linked}" \
PREF_LOSS_TYPE="${PREF_LOSS_TYPE:-lagrangian}" \
PREF_STOPGRAD_POSITIVE="${PREF_STOPGRAD_POSITIVE:-1}" \
PROJECT="${PROJECT:-thesis-safetygym}" \
WANDB_MODE="${WANDB_MODE:-online}" \
EXP_PREFIX="$EXP_PREFIX" \
EXP_NAME="$EXP_NAME" \
/home/benjamin/thesis/scripts/run_safetycar_minimal_human_ready_local.sh
