#!/usr/bin/env bash
set -euo pipefail

ROOT="/home/benjamin/thesis"
cd "$ROOT"

for arg in "$@"; do
  case "$arg" in
    *=*)
      export "$arg"
      ;;
    *)
      echo "Unsupported argument: $arg" >&2
      exit 2
      ;;
  esac
done

STUDENT_INIT_CKPT="${STUDENT_INIT_CKPT:-/home/benjamin/thesis/models/safetygym_minimal/safetycar_min_human_ready_confirm50k_20260402_183507/step_25000.pt}"
GOAL_EXPERT_CKPT="${GOAL_EXPERT_CKPT:-/home/benjamin/thesis/models/safetygym_minimal/safetycar_min_human_ready_confirm50k_20260402_183507/step_25000.pt}"
SAFE_EXPERT_CKPT="${SAFE_EXPERT_CKPT:-/home/benjamin/thesis/models/safetygym_minimal/safetycar_min_safe_dense_cost001_step_big_noviz_20260402_200356/step_5000.pt}"
TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
NET_TAG="${NET_TAG:-big}"
TEACHER_TAG="${TEACHER_TAG:-hybrid_clear008}"
TOTAL_TIMESTEPS="${TOTAL_TIMESTEPS:-20000}"
CHECKPOINT_INTERVAL="${CHECKPOINT_INTERVAL:-5000}"

EXP_PREFIX="${EXP_PREFIX:-safetycar_min_hil_hybrid_teacher_${NET_TAG}_${TEACHER_TAG}}"

/home/benjamin/thesis/scripts/run_safetycar_minimal_human_ready_local.sh \
  TIMESTAMP="$TIMESTAMP" \
  EXP_PREFIX="$EXP_PREFIX" \
  VARIANT="${VARIANT:-hilserl}" \
  TOTAL_TIMESTEPS="$TOTAL_TIMESTEPS" \
  CHECKPOINT_INTERVAL="$CHECKPOINT_INTERVAL" \
  MODULE_IMPL="${MODULE_IMPL:-custom}" \
  INIT_CHECKPOINT_PATH="$STUDENT_INIT_CKPT" \
  LOAD_ACTOR_FROM_CHECKPOINT=1 \
  LOAD_CRITIC_FROM_CHECKPOINT=1 \
  LOAD_CRITIC_TARGET_FROM_CHECKPOINT=1 \
  LOAD_ALPHA_FROM_CHECKPOINT=1 \
  LOAD_OPTIMIZER_STATE_FROM_CHECKPOINT=0 \
  SAVE_OPTIMIZER_STATE_IN_CHECKPOINTS="${SAVE_OPTIMIZER_STATE_IN_CHECKPOINTS:-0}" \
  LEARNING_STARTS=0 \
  REWARD_MODE="${REWARD_MODE:-dense}" \
  STEP_PENALTY="${STEP_PENALTY:--0.001}" \
  COST_PENALTY="${COST_PENALTY:-0.0}" \
  ACTOR_LEARNING_RATE="${ACTOR_LEARNING_RATE:-2e-5}" \
  CRITIC_LEARNING_RATE="${CRITIC_LEARNING_RATE:-1e-4}" \
  ACTOR_HIDDEN_DIM="${ACTOR_HIDDEN_DIM:-512}" \
  CRITIC_HIDDEN_DIM="${CRITIC_HIDDEN_DIM:-1024}" \
  OBS_NORMALIZATION="${OBS_NORMALIZATION:-1}" \
  SCALE_ACTOR_TO_ENV_BOUNDS="${SCALE_ACTOR_TO_ENV_BOUNDS:-1}" \
  CAR_WHEEL_COMMAND_LIMIT="${CAR_WHEEL_COMMAND_LIMIT:-2.0}" \
  CAR_FORCE_SCALE="${CAR_FORCE_SCALE:-2.0}" \
  RESEED_ON_EPISODE_RESET=0 \
  USE_INTERVENTION=1 \
  HUMAN_INPUT_DEVICE=expert_switch \
  EXPERT_CHECKPOINT_PATH="$GOAL_EXPERT_CKPT" \
  EXPERT_SAFE_CHECKPOINT_PATH="$SAFE_EXPERT_CKPT" \
  EXPERT_SWITCH_CLEARANCE_THRESHOLD="${EXPERT_SWITCH_CLEARANCE_THRESHOLD:-0.08}" \
  TEACHER_OVERRIDE_CLEARANCE_THRESHOLD=-1.0 \
  DEMO_SAMPLE_RATIO="${DEMO_SAMPLE_RATIO:-0.5}" \
  PREF_CAPACITY=0 \
  PREF_SAMPLE_RATIO=0.0 \
  PREF_RANK_WEIGHT=0.0 \
  VIZ_ON_CHECKPOINT=0 \
  EVAL_SAVE_EPISODE_PLOTS=0 \
  RENDER_MODE=none \
  NUM_EVAL_EPISODES="${NUM_EVAL_EPISODES:-10}" \
  LOG_INTERVAL="${LOG_INTERVAL:-2000}"
