#!/usr/bin/env bash
set -euo pipefail

ROOT="/home/benjamin/thesis"
cd "$ROOT"

for arg in "$@"; do
  case "$arg" in
    *=*)
      export "$arg"
      ;;
    *)
      echo "Unsupported argument: $arg" >&2
      exit 2
      ;;
  esac
done

SAFE_BASE_CKPT="${SAFE_BASE_CKPT:-/home/benjamin/thesis/models/safetygym_minimal/safetycar_min_safe_dense_big_50k_long_20260402_211500/final.pt}"
TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
NET_TAG="${NET_TAG:-big}"
SAFETY_TAG="${SAFETY_TAG:-clearance6_margin015}"
TOTAL_TIMESTEPS="${TOTAL_TIMESTEPS:-20000}"
CHECKPOINT_INTERVAL="${CHECKPOINT_INTERVAL:-5000}"

EXP_PREFIX="${EXP_PREFIX:-safetycar_min_stage2_safebase_${SAFETY_TAG}_${NET_TAG}}"

/home/benjamin/thesis/scripts/run_safetycar_minimal_human_ready_local.sh \
  TIMESTAMP="$TIMESTAMP" \
  EXP_PREFIX="$EXP_PREFIX" \
  VARIANT=plain \
  TOTAL_TIMESTEPS="$TOTAL_TIMESTEPS" \
  CHECKPOINT_INTERVAL="$CHECKPOINT_INTERVAL" \
  MODULE_IMPL="${MODULE_IMPL:-custom}" \
  INIT_CHECKPOINT_PATH="$SAFE_BASE_CKPT" \
  LOAD_ACTOR_FROM_CHECKPOINT=1 \
  LOAD_CRITIC_FROM_CHECKPOINT=1 \
  LOAD_CRITIC_TARGET_FROM_CHECKPOINT=1 \
  LOAD_ALPHA_FROM_CHECKPOINT=1 \
  LOAD_OPTIMIZER_STATE_FROM_CHECKPOINT=0 \
  SAVE_OPTIMIZER_STATE_IN_CHECKPOINTS="${SAVE_OPTIMIZER_STATE_IN_CHECKPOINTS:-0}" \
  LEARNING_STARTS=0 \
  REWARD_MODE="${REWARD_MODE:-dense}" \
  STEP_PENALTY="${STEP_PENALTY:--0.001}" \
  COST_PENALTY="${COST_PENALTY:--0.01}" \
  COST_PENALTY_WARMUP_STEPS="${COST_PENALTY_WARMUP_STEPS:-0}" \
  COST_PENALTY_RAMP_STEPS="${COST_PENALTY_RAMP_STEPS:-10000}" \
  CLEARANCE_PENALTY_SCALE="${CLEARANCE_PENALTY_SCALE:-6.0}" \
  CLEARANCE_MARGIN="${CLEARANCE_MARGIN:-0.15}" \
  CLEARANCE_PENALTY_POWER="${CLEARANCE_PENALTY_POWER:-1.0}" \
  FORWARD_REWARD_SCALE=0.0 \
  BACKWARD_PENALTY_SCALE=0.0 \
  HEADING_REWARD_SCALE=0.0 \
  ACTOR_LEARNING_RATE="${ACTOR_LEARNING_RATE:-2e-5}" \
  CRITIC_LEARNING_RATE="${CRITIC_LEARNING_RATE:-1e-4}" \
  ACTOR_HIDDEN_DIM="${ACTOR_HIDDEN_DIM:-512}" \
  CRITIC_HIDDEN_DIM="${CRITIC_HIDDEN_DIM:-1024}" \
  OBS_NORMALIZATION="${OBS_NORMALIZATION:-1}" \
  SCALE_ACTOR_TO_ENV_BOUNDS="${SCALE_ACTOR_TO_ENV_BOUNDS:-1}" \
  CAR_WHEEL_COMMAND_LIMIT="${CAR_WHEEL_COMMAND_LIMIT:-2.0}" \
  CAR_FORCE_SCALE="${CAR_FORCE_SCALE:-2.0}" \
  RESEED_ON_EPISODE_RESET=0 \
  PREF_CAPACITY=0 \
  PREF_SAMPLE_RATIO=0.0 \
  PREF_RANK_WEIGHT=0.0 \
  DEMO_SAMPLE_RATIO=0.0 \
  VIZ_ON_CHECKPOINT=0 \
  EVAL_SAVE_EPISODE_PLOTS=0 \
  RENDER_MODE=none \
  NUM_EVAL_EPISODES="${NUM_EVAL_EPISODES:-10}" \
  LOG_INTERVAL="${LOG_INTERVAL:-2000}"
