#!/usr/bin/env bash
set -euo pipefail

ROOT="/home/benjamin/thesis"
cd "$ROOT"

for arg in "$@"; do
  case "$arg" in
    *=*)
      export "$arg"
      ;;
    *)
      echo "Unsupported argument: $arg" >&2
      exit 2
      ;;
  esac
done

TIMESTAMP="${TIMESTAMP:-$(date +%Y%m%d_%H%M%S)}"
EXP_NAME="${EXP_NAME:-safetycar_goal2_softplus_clearance_m000_s11_${TIMESTAMP}}"
WANDB_GROUP="${WANDB_GROUP:-$EXP_NAME}"

echo "Configured Safety-Gym Goal2 softplus-clearance training"
echo "repo:       $ROOT"
echo "run:        $EXP_NAME"
echo "group:      $WANDB_GROUP"
echo "env:        ${ENV_NAME:-SafetyCarGoal2-v0}"
echo "reward:     ${REWARD_MODE:-dense_plus_sparse} + softplus clearance"
echo "clearance:  margin=${CLEARANCE_MARGIN:-0.0}, scale=${CLEARANCE_PENALTY_SCALE:-1.1}, temp=${CLEARANCE_PENALTY_TEMPERATURE:-0.001}"
echo "step pen:   ${STEP_PENALTY:--0.001}"
echo "action:     raw_wheels limit=${CAR_WHEEL_COMMAND_LIMIT:-1.0}, force=${CAR_FORCE_SCALE:-1.0}"

./scripts/run_safetycar_minimal_human_ready_local.sh \
  "EXP_NAME=$EXP_NAME" \
  "EXP_PREFIX=safetycar_goal2_softplus_clearance_m000_s11" \
  "WANDB_GROUP=$WANDB_GROUP" \
  "WANDB_MODE=${WANDB_MODE:-online}" \
  "PROJECT=${PROJECT:-thesis-safetygym}" \
  "ENV_NAME=${ENV_NAME:-SafetyCarGoal2-v0}" \
  "VARIANT=${VARIANT:-plain}" \
  "MODULE_IMPL=${MODULE_IMPL:-custom}" \
  "USE_LAYER_NORM=${USE_LAYER_NORM:-1}" \
  "ACTOR_HIDDEN_DIM=${ACTOR_HIDDEN_DIM:-512}" \
  "CRITIC_HIDDEN_DIM=${CRITIC_HIDDEN_DIM:-1024}" \
  "REWARD_MODE=${REWARD_MODE:-dense_plus_sparse}" \
  "STEP_PENALTY=${STEP_PENALTY:--0.001}" \
  "COST_PENALTY=${COST_PENALTY:-0.0}" \
  "CLEARANCE_PENALTY_MODE=${CLEARANCE_PENALTY_MODE:-softplus}" \
  "CLEARANCE_MARGIN=${CLEARANCE_MARGIN:-0.0}" \
  "CLEARANCE_PENALTY_SCALE=${CLEARANCE_PENALTY_SCALE:-1.1}" \
  "CLEARANCE_PENALTY_TEMPERATURE=${CLEARANCE_PENALTY_TEMPERATURE:-0.001}" \
  "CLEARANCE_PENALTY_WARMUP_STEPS=${CLEARANCE_PENALTY_WARMUP_STEPS:-0}" \
  "CLEARANCE_PENALTY_RAMP_STEPS=${CLEARANCE_PENALTY_RAMP_STEPS:-0}" \
  "FORWARD_REWARD_SCALE=${FORWARD_REWARD_SCALE:-0.0}" \
  "BACKWARD_PENALTY_SCALE=${BACKWARD_PENALTY_SCALE:-0.0}" \
  "HEADING_REWARD_SCALE=${HEADING_REWARD_SCALE:-0.0}" \
  "ADAPTIVE_SAFETY_CURRICULUM=${ADAPTIVE_SAFETY_CURRICULUM:-0}" \
  "TERMINATE_ON_GOAL=${TERMINATE_ON_GOAL:-0}" \
  "TOTAL_TIMESTEPS=${TOTAL_TIMESTEPS:-200000}" \
  "LEARNING_STARTS=${LEARNING_STARTS:-5000}" \
  "CHECKPOINT_INTERVAL=${CHECKPOINT_INTERVAL:-10000}" \
  "LOG_INTERVAL=${LOG_INTERVAL:-2000}" \
  "NUM_EVAL_EPISODES=${NUM_EVAL_EPISODES:-10}" \
  "NUM_UPDATES=${NUM_UPDATES:-2}" \
  "POLICY_FREQUENCY=${POLICY_FREQUENCY:-2}" \
  "GAMMA=${GAMMA:-0.99}" \
  "OBS_NORMALIZATION=${OBS_NORMALIZATION:-1}" \
  "RESEED_ON_EPISODE_RESET=${RESEED_ON_EPISODE_RESET:-0}" \
  "CAR_WHEEL_COMMAND_LIMIT=${CAR_WHEEL_COMMAND_LIMIT:-1.0}" \
  "CAR_FORCE_SCALE=${CAR_FORCE_SCALE:-1.0}" \
  "CAR_ACTION_MODE=${CAR_ACTION_MODE:-raw_wheels}" \
  "LOAD_ACTOR_FROM_CHECKPOINT=0" \
  "LOAD_CRITIC_FROM_CHECKPOINT=0" \
  "LOAD_CRITIC_TARGET_FROM_CHECKPOINT=0" \
  "LOAD_ALPHA_FROM_CHECKPOINT=0" \
  "LOAD_OPTIMIZER_STATE_FROM_CHECKPOINT=0" \
  "PREF_SAMPLE_RATIO=0.0" \
  "PREF_REPLAY_SAMPLE_RATIO=0.0" \
  "PREF_RANK_WEIGHT=0.0" \
  "DEMO_SAMPLE_RATIO=0.0" \
  "PREFILL_DEMO_EPISODES=0" \
  "EVAL_SAVE_EPISODE_PLOTS=${EVAL_SAVE_EPISODE_PLOTS:-1}" \
  "VIZ_ON_CHECKPOINT=${VIZ_ON_CHECKPOINT:-0}" \
  "$@"
